a=10
b=76
print(a+b)
print("Sum:", a + b)
print("Difference:", b - a)
print("Product:", a * b)
print("Quotient:", b / a)
print("Integer Division:", b // a)
print("Remainder:", b % a)
print("Exponentiation:", a ** 2)
print("Combined Operations:", (a + b) * (b - a))
print("Increment a by 5:", a + 5)
print("Decrement b by 10:", b - 10)
print("Double a:", a * 2)
print("Half of b:", b / 2)
print("a squared plus b squared:", a**2 + b**2)
print("Average of a and b:", (a + b) / 2)
print("a multiplied by b minus a:", a * b - a)
print("b divided by a plus b:", b / a + b)
print("a modulo 3:", a % 3)
print("b modulo 7:", b % 7)
print("a to the power of 3:", a ** 3)
print("b to the power of 0.5 (square root):", b ** 0.5)


print("Bitwise AND of a and b:", a & b)
print("Bitwise OR of a and b:", a | b)  
print("Bitwise XOR of a and b:", a ^ b)
print("Bitwise NOT of a:", ~a)
print("Left shift a by 2:", a << 2)
print("Right shift b by 3:", b >> 3)


print("Logical AND (a > 5 and b < 100):", (a > 5) and (b < 100))
print("Logical OR (a < 5 or b < 100):", (a < 5) or (b < 100))
print("Logical NOT (not (a > 5)):", not (a > 5))
print("Is a equal to b?:", a == b)
print("Is a not equal to b?:", a != b)
print("Is a greater than b?:", a > b)
print("Is a less than b?:", a < b)